### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by OlgaRadDev** [OlgaRadDev/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Collaborator-bsa20** [comment]
https://www.donaldjtrump.com/get-involved/sms
https://www.facebook.com/DonaldTrump/
https://twitter.com/realDonaldTrump
https://www.instagram.com/realdonaldtrump/
https://www.youtube.com/channel/UCAql2DyGU2un1Ei2nMYsqOA

**Comment by OlgaRadDev** [comment]
Great!!!
