### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by OlgaRadDev** [OlgaRadDev/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Collaborator-bsa20** [comment]
Donald John Trump is the 45th and current President of the United States

Born in Queens, New York, in 1946, Trump became involved in large, profitable building projects in Manhattan. In 1980, he opened the Grand Hyatt New York, which made him the city's best-known developer. 

At age 13, Trump’s parents sent him to the New York Military Academy, hoping the discipline of the school would channel his energy in a positive manner. He did well at the academy, both socially and academically, rising to become a star athlete and student leader by the time he graduated in 1964.

Trump entered Fordham University in 1964. He transferred to the Wharton School of Finance at the University of Pennsylvania two years later and graduated in 1968 with a degree in economics. 

In 1977, Trump married his first wife Ivana Trump, (née Zelnickova Winklmayr), a New York fashion model who had been an alternate on the 1972 Czech Olympic Ski Team. 

In 1987, Trump published the book The Art of the Deal, co-authored with Tony Schwartz. In the book, Trump describes how he successfully makes business deals.

In 1990, Trump asserted his own net worth in the neighborhood of $1.5 billion.

In 1993 Trump married his second wife, Marla Maples, an actress with whom he had been involved for some time and already had a daughter, Tiffany.

Trump has five children. He and his first wife, Ivana Trump, had three children together: Donald Trump Jr., born in 1977; Ivanka Trump, born in 1981, and Eric Trump, born in 1984. Trump and his second wife, Marla Maples, had daughter Tiffany Trump in 1993. And current wife Melania Trump gave birth to Trump’s youngest child, Barron William Trump, in March 2006.

Trump's sons — Donald Jr. and Eric— work as executive vice presidents for The Trump Organization. They took over the family business while their father serves as president. 

In 2004, Trump began starring in the hit NBC reality series The Apprentice. Trump turned his attention to politics, and in 2015 he announced his candidacy for president of the United States on the Republican ticket. 

After winning a majority of the primaries and caucuses, Trump became the official Republican candidate for president on July 19, 2016. That November, Trump was elected the 45th President of the United States

On June 18, 2019, Trump launched his 2020 reelection bid with one of his patented rallies at the 20,000-seat Amway Center in Orlando, Florida.

**Comment by OlgaRadDev** [comment]
Many thanks!!!
